### ISSUE TITLE
listunspent doc missing include_unsafe parameter

### ISSUE THREAD

**Issue by howard-stearns** [ElementsProject/elementsbp-api-reference#3]
The documentation for listunspent lists 4 parameters ending in asset string, but it is missing the include_unsafe boolean 4th parameter.

**Comment by howard-stearns** [comment]
Also, the doc and the code don't seem to agree with each other about the interpretation of the asset  parameter:

- api reference says default is "*" and that this means "all of them"
- "help" says default is "bitcoin"
- Actual behavior of code seems to be that the default is the empty string, meaning "all of them". Explicitly passing "*" gives "Unknown label and invalid asset hex: * (-4)"

**Comment by instagibbs** [comment]
Thanks for the report. This is a mixture of upstream issues that have been patched recently and screwups on our end. I'll take it on, thanks.

**Comment by instagibbs** [comment]
Fixed help text in elements to reflect reality: https://github.com/ElementsProject/elements/pull/284

**Comment by instagibbs** [comment]
Also PR'd a fix for the documentation
